name: auto green

on:
  push:
    branches:
      - master
  schedule:
    - cron: "1 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto commit
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am "a commit every day, keep your girlfriend far away"

      - name: Auto Push
        run: |
          git remote set-url origin https://justjavac:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
